# Generated by Django 4.1.2 on 2022-10-28 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_spam_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spam_Contacts',
            new_name='SpamContacts',
        ),
    ]
